version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:8080
  apache:
    image: php:apache
    restart: always
    volumes:
        - /C:/Laravel Project/car-rental-service
        - ./apache-config.conf:/etc/apache2/conf-available/custom-config.conf
    ports:
        - "80:443"
